services:
  #nextjs service
  nextapp:
    container_name: nextapp
    image: dragonfruit-grader-nextapp:1.0.0
    build:
      context: .
      dockerfile: dockerfiles/next.Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - flaskapp

  # flask service
  flaskapp:
    container_name: flaskapp
    image: dragonfruit-grader-flaskapp:1.0.0
    build:
      context: .
      dockerfile: dockerfiles/flask.Dockerfile
    ports:
      - 8000:8000

